### ISSUE TITLE
error when trying to run it

### ISSUE THREAD

**Issue by fabiolin** [DiRaizel/navigation_with_mapbox#5]
I am getting the following error:

E/FrameEvents(25070): updateAcquireFence: Did not find frame.
E/FrameEvents(25070): updateAcquireFence: Did not find frame.
E/FrameEvents(25070): updateAcquireFence: Did not find frame.
W/br.com.wmb.coi(25070): Accessing hidden field Landroid/graphics/Typeface;->sSystemFontMap:Ljava/util/Map; (greylist, reflection, allowed)
I/Mbgl-FontUtils(25070): Couldn't map font family for local ideograph, using sans-serif instead
I/Mapbox  (25070): [MapboxReachability]: Application permission for ACCESS_NETWORK_STATE granted
W/CrashReporter(25070): Root directory doesn't exist
W/Mapbox  (25070): [events_service]: Events configuration file [/data/user/0/br.com.wmb.coi/files/.mapbox/events_config] doesn't exist
W/TelemetryUtils(25070): java.lang.SecurityException: getDataNetworkTypeForSubscriber
I/DecorView(25070): [INFO] isPopOver=false, config=true
I/DecorView(25070): updateCaptionType >> DecorView@8ae657b[], isFloating=false, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=true
D/DecorView(25070): setCaptionType = 0, this = DecorView@8ae657b[]
W/br.com.wmb.coi(25070): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/br.com.wmb.coi(25070): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/Mapbox  (25070): [nav-sdk]: [RoutingTilesFiles] Initial size is 3488 bytes
I/Mapbox  (25070): [nav-sdk]: [HistoryFiles] Initial size is 3488 bytes
I/Mapbox  (25070): [nav-sdk]: [RoutingTilesFiles] Initial size is 3488 bytes
I/Mapbox  (25070): [nav-native]: PersistentConfig path: /data/user/0/br.com.wmb.coi/files/mbx_nav/tiles/navigation/config.json
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
I/Mapbox  (25070): [nav-native]: PersistentConfig path: /data/user/0/br.com.wmb.coi/files/mbx_nav/tiles/navigation/config.json
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
I/Mapbox  (25070): [nav-native]: Tiles path = "/data/user/0/br.com.wmb.coi/files/mbx_nav/tiles"
I/Mapbox  (25070): [nav-native]: TileStore instance wasn't passed
I/Mapbox  (25070): [nav-native]: Endpoint config = "{"dataSet":"mapbox/driving-traffic","host":"https://api.mapbox.com","isFallback":false,"minDiffInDaysToConsiderServerVersion":56,"navigatorVersion":"115.0.0","token":"***...*","userAgent":"MapboxNavigationNative","version":"","versionBeforeFallback":""}"
I/Mapbox  (25070): [nav-native]: Creating navigator v.115.0.0
I/Mapbox  (25070): [nav-native]: Refreshing alternatives after network is regained
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
D/SensorManager(25070): registerListener :: 11, bmi26x Accelerometer Non-wakeup, 20000, 0, com.mapbox.navigator.IMUServiceImpl@2dcb70d
D/SensorManager(25070): registerListener :: 21, mmc5603x Magnetometer Non-wakeup, 20000, 0, com.mapbox.navigator.IMUServiceImpl@2dcb70d
D/SensorManager(25070): registerListener :: 111, Rotation Vector  Non-wakeup, 20000, 0, com.mapbox.navigator.IMUServiceImpl@2dcb70d
D/SensorManager(25070): registerListener :: 91, gravity  Non-wakeup, 20000, 0, com.mapbox.navigator.IMUServiceImpl@2dcb70d
D/SensorManager(25070): registerListener :: 41, bmi26x Gyroscope Non-wakeup, 20000, 0, com.mapbox.navigator.IMUServiceImpl@2dcb70d
I/MBNNIMUService(25070): This device has no pressure sensor
D/SensorManager(25070): registerListener :: 11, bmi26x Accelerometer Non-wakeup, 200000, 0, android.view.OrientationEventListener$SensorEventListenerImpl@8fbbc1a
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
W/Mapbox  (25070): [valhalla]: No metadata found for tiles
D/AndroidRuntime(25070): Shutting down VM
E/AndroidRuntime(25070): FATAL EXCEPTION: main
E/AndroidRuntime(25070): Process: br.com.wmb.coi, PID: 25070
E/AndroidRuntime(25070): java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Lcom/mapbox/navigation/ui/voice/options/VoiceInstructionsPlayerOptions;Lcom/mapbox/navigation/ui/voice/api/AsyncAudioFocusDelegate;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lcom/mapbox/navigation/ui/voice/api/MapboxVoiceInstructionsPlayer; or its super classes (declaration of 'com.mapbox.navigation.ui.voice.api.MapboxVoiceInstructionsPlayer' appears in /data/app/~~6MiUaqgIF403SDBkgqsRug==/br.com.wmb.coi-INJFtG4LVNPwiC0RocLd1Q==/base.apk!classes7.dex)
E/AndroidRuntime(25070): 	at com.navigation.with.mapbox.navigation_with_mapbox.views.FullscreenActivity.onCreate(FullscreenActivity.kt:579)
E/AndroidRuntime(25070): 	at android.app.Activity.performCreate(Activity.java:8215)
E/AndroidRuntime(25070): 	at android.app.Activity.performCreate(Activity.java:8199)
E/AndroidRuntime(25070): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(25070): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3824)
E/AndroidRuntime(25070): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4027)
E/AndroidRuntime(25070): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(25070): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(25070): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(25070): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
E/AndroidRuntime(25070): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(25070): 	at android.os.Looper.loop(Looper.java:247)
E/AndroidRuntime(25070): 	at android.app.ActivityThread.main(ActivityThread.java:8676)
E/AndroidRuntime(25070): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25070): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(25070): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process (25070): Sending signal. PID: 25070 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by fabiolin** [comment]
this is a conflict with another mapbox SDK in the same project
